//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorías
    {
        public Categorías()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int IdCategoría { get; set; }
        public string NombreCategoría { get; set; }
        public string Descripción { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
