//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Pedidos = new HashSet<Pedido>();
        }
    
        public string IdCliente { get; set; }
        public string NombreCompañía { get; set; }
        public string NombreContacto { get; set; }
        public string CargoContacto { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Región { get; set; }
        public string CódPostal { get; set; }
        public string País { get; set; }
        public string Teléfono { get; set; }
        public string Fax { get; set; }
    
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
