//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Pedidos = new HashSet<Pedido>();
        }
    
        public int IdEmpleado { get; set; }
        public string Apellidos { get; set; }
        public string Nombre { get; set; }
        public string Cargo { get; set; }
        public string Tratamiento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaContratación { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Región { get; set; }
        public string CódPostal { get; set; }
        public string País { get; set; }
        public string TelDomicilio { get; set; }
        public string Extensión { get; set; }
        public string Foto { get; set; }
        public string Notas { get; set; }
        public Nullable<int> Jefe { get; set; }
    
        public virtual ICollection<Pedido> Pedidos { get; set; }
    }
}
