//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Detalles = new HashSet<Detalle>();
        }
    
        public int IdPedido { get; set; }
        public string IdCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaEnvío { get; set; }
        public Nullable<int> FormaEnvío { get; set; }
        public Nullable<decimal> Cargo { get; set; }
        public string Destinatario { get; set; }
        public string DirecciónDestinatario { get; set; }
        public string CiudadDestinatario { get; set; }
        public string RegiónDestinatario { get; set; }
        public string CódPostalDestinatario { get; set; }
        public string PaísDestinatario { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle> Detalles { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
