//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprendiendoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        public Proveedore()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int IdProveedor { get; set; }
        public string NombreCompañía { get; set; }
        public string NombreContacto { get; set; }
        public string CargoContacto { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Región { get; set; }
        public string CódPostal { get; set; }
        public string País { get; set; }
        public string Teléfono { get; set; }
        public string Fax { get; set; }
        public string PáginaPrincipal { get; set; }
    
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
